spring.application.name=restaurant-reservation-system

spring.datasource.url=jdbc:mysql://localhost:3306/restaurant_reservation_db
spring.datasource.username=dev_user
spring.datasource.password=Dev@2026#
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

auth.jwt.secret=ZHVtbXlfc2VjcmV0X2tleV9mb3JfdGVzdGluZ19wdXJwb3NlX29ubHlfMTIzNDU2
auth.jwt.expiration=86400000